### ISSUE TITLE
Update price comparison with real-time market pricing

### ISSUE THREAD

**Issue by mjspadaro** [Akashlytics/akashlytics#11]
I really love this tool! Would be great to see some way to see statistics about the market rates for leases on active deployments (in uakt/block and akt/month) - for those looking to deploy on Akash, this would be a nice feature to be able to estimate and budget for a deployment, and for providers to set their bids based on market rates.

**Comment by mbeauchamp7** [comment]
Hey, thanks for the feedback! Yes that's a good idea, I will put it in the TODO list. Currently working on a deploy ui though so might take some time.
